app:
  env: dev
  shadow_mode: true  # still evaluate, but do not enforce except for overrides
  shadow_overrides:   # rules that ALWAYS enforce even in shadow
    - "IL-AI-1.1"
    - "SECRETS-EXFIL"

notifiers:
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#jimini-alerts"
    username: "Jimini"
    icon_emoji: ":shield:"

  teams:
    enabled: false
    webhook_url: "${TEAMS_WEBHOOK_URL}"

siem:
  jsonl:
    enabled: true
    path: "logs/jimini_events.jsonl"

  splunk_hec:
    enabled: false
    url: "https://splunk.example.com:8088/services/collector"
    token: "${SPLUNK_HEC_TOKEN}"
    sourcetype: "jimini:event"
    verify_tls: true

  elastic:
    enabled: false
    url: "https://elastic.example.com:9200/jimini-events/_doc"
    basic_auth_user: "${ELASTIC_USER}"
    basic_auth_pass: "${ELASTIC_PASS}"
    verify_tls: true

otel:
  enabled: false
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}" # e.g. http://localhost:4317
  service_name: "jimini"
  resource:
    environment: "dev"
