name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Unit tests (Py 3.12)
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff .

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q
